AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cloud-to-do-app

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  GymClassTrackerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: to-do-table
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST 

  CrudToDoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda_functions/crud_to_do/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        ToDo:
          Type: Api 
          Properties:
            Path: /to-dos
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ToDoApi:
    Description: "API Gateway endpoint URL for Prod stage for To Do function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/to-dos/"
  CrudToDoFunction:
    Description: "for To Do List Lambda Function ARN"
    Value: !GetAtt CrudToDoFunction.Arn
  CrudToDoFunctionIamRole:
    Description: "Implicit IAM Role created for To Do LIst function"
    Value: !GetAtt CrudToDoFunctionRole.Arn
